### ISSUE TITLE
cloth-config2 6.0.0

### ISSUE THREAD

**Issue by oFallen** [Bstn1802/AutoReconnect#34]
Hi, When i run my fabric with Autoreconnect mod i am getting this error.

**Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config2, version 6.0.0 or later.
Unmet dependency listing:
	 - Mod 'AutoReconnect' (autoreconnect) 2.1.0-beta requires version 6.0.0 or later of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)**
	
	Fabric Loader ver: fabric-loader-0.14.10-1.19.2
	List of mods:
	autoreconnect-2.1.0-beta.jar
	cloth-config-6.4.90-forge.jar
	fabric-api-0.66.0+1.19.2.jar
	modmenu-4.1.0.jar

**Comment by Bstn1802** [comment]
> cloth-config-6.4.90-forge.jar

...
"forge"
xD
Use the fabric version (:
