### ISSUE TITLE
Error with it trying to reconnect, but unable

### ISSUE THREAD

**Issue by DanielEverett1** [Bstn1802/AutoReconnect#45]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.delays" is null

`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/31/23, 12:19 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.delays" is null
	at autoreconnect.config.ModConfig.getDelays(ModConfig.java:25)
	at autoreconnect.AutoReconnect.onDisconnected(AutoReconnect.java:111)
	at autoreconnect.event.DisconnectListener.lambda$static$0(DisconnectListener.java:11)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at autoreconnect.event.DisconnectListener.lambda$static$1(DisconnectListener.java:11)
	at net.minecraft.class_419.handler$zzb000$autoreconnect$init(class_419.java:523)
	at net.minecraft.class_419.<init>(class_419.java:19)
	at net.minecraft.class_634.method_10839(class_634.java:717)
	at net.minecraft.class_2535.method_10768(class_2535.java:413)
	at net.minecraft.class_636.method_2927(class_636.java:276)
	at net.minecraft.class_310.method_1574(class_310.java:1698)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at autoreconnect.config.ModConfig.getDelays(ModConfig.java:25)
	at autoreconnect.AutoReconnect.onDisconnected(AutoReconnect.java:111)
	at autoreconnect.event.DisconnectListener.lambda$static$0(DisconnectListener.java:11)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at autoreconnect.event.DisconnectListener.lambda$static$1(DisconnectListener.java:11)
	at net.minecraft.class_419.handler$zzb000$autoreconnect$init(class_419.java:523)
	at net.minecraft.class_419.<init>(class_419.java:19)
	at net.minecraft.class_634.method_10839(class_634.java:717)
	at net.minecraft.class_2535.method_10768(class_2535.java:413)
	at net.minecraft.class_636.method_2927(class_636.java:276)

-- Last reload --
Details:
	Reload number: 4
	Reload reason: manual
	Finished: No
	Packs: Default, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by Bstn1802** [comment]
Sorry for the late response. This has to have been such an old version of this mod. Even at that time it must have been totally out of date and I'm not really working on older versions anymore, I'm glad if I can keep up with the newer ones. For that reason I am closing this issue.

Btw, code blocks a tripple back ticks, not single ones
