### ISSUE TITLE
1.20 Compatibility

### ISSUE THREAD

**Issue by thomasdaley2** [Bstn1802/AutoReconnect#51]
I believe this mod may be dead but if you're still out there is there a chance this will be updated?  I love this mod

**Comment by Bstn1802** [comment]
No... well, yes kind of, I've been quite busy but I'm hoping to get back to it very soon!
Until then: Others have been updating it themselves, just check some of the issues and pull request, I even found a .jar somewhere there which seemed to work fine, but I haven't been able to do much testing so far

**Comment by HyCore** [comment]
> No... well, yes kind of, I've been quite busy but I'm hoping to get back to it very soon! Until then: Others have been updating it themselves, just check some of the issues and pull request, I even found a .jar somewhere there which seemed to work fine, but I haven't been able to do much testing so far

The 1.20.1 .jar mod works fine indeed, No issue detect yet except one with the multimc auto connect feature. Other than that, it's running smoothly.

(log of the crash)
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-07-22 15:54:47
Description: Ticking screen

java.lang.NullPointerException: Cannot invoke "autoreconnect.reconnect.ReconnectStrategy.nextAttempt()" because "this.reconnectStrategy" is null
	at autoreconnect.AutoReconnect.startCountdown(AutoReconnect.java:68)
	at net.minecraft.class_419.handler$zzc001$autoreconnect$constructor(class_419.java:1039)
	at net.minecraft.class_419.<init>(class_419.java:18)
	at net.minecraft.class_634.method_10839(class_634.java:831)
	at net.minecraft.class_2535.method_10768(class_2535.java:435)
	at net.minecraft.class_412.method_25393(class_412.java:116)
	at net.minecraft.class_310.method_1572(class_310.java:1872)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_310.method_1574(class_310.java:1872)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	```

**Comment by Bstn1802** [comment]
1.20 has been released yesterday and it also seems to work for 1.20.1
